# Generated by Django 6.0.5 on 2026-05-30 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('retail_points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('dealer', models.ForeignKey(limit_choices_to={'point_type': 'DEALER'}, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='retail_points.retailpoint')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_stocks', to='products.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dealer', 'product'), name='unique_dealer_product')],
            },
        ),
    ]
