# Generated by Django 6.0.5 on 2026-05-30 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_product_brand_and_more'),
        ('retail_points', '0002_alter_employee_options_alter_retailpoint_options_and_more'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealerstock',
            options={'verbose_name': 'Учёт наличия', 'verbose_name_plural': 'Учёт наличия'},
        ),
        migrations.AlterField(
            model_name='dealerstock',
            name='dealer',
            field=models.ForeignKey(limit_choices_to={'point_type': 'DEALER'}, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='retail_points.retailpoint', verbose_name='Дилерский центр'),
        ),
        migrations.AlterField(
            model_name='dealerstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_stocks', to='products.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='dealerstock',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
