# Generated by Django 6.0.5 on 2026-05-30 13:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('point_type', models.CharField(choices=[('HEAD', 'Head office'), ('DEALER', 'Dealer center')], max_length=10)),
                ('daily_revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetailPointAddress',
            fields=[
                ('retail_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='address', serialize=False, to='retail_points.retailpoint')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('house_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddConstraint(
            model_name='retailpoint',
            constraint=models.UniqueConstraint(condition=models.Q(('point_type', 'HEAD')), fields=('point_type',), name='one_head_only'),
        ),
        migrations.AddField(
            model_name='employee',
            name='retail_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='retail_points.retailpoint'),
        ),
    ]
