# Generated by Django 6.0.5 on 2026-05-30 14:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_points', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='retailpoint',
            options={'verbose_name': 'Торговая точка', 'verbose_name_plural': 'Торговые точки'},
        ),
        migrations.AlterModelOptions(
            name='retailpointaddress',
            options={'verbose_name': 'Адрес торговой точки', 'verbose_name_plural': 'Адреса торговых точек'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='retail_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='retail_points.retailpoint', verbose_name='Торговая точка'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='retailpoint',
            name='daily_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Выручка за день'),
        ),
        migrations.AlterField(
            model_name='retailpoint',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='retailpoint',
            name='point_type',
            field=models.CharField(choices=[('HEAD', 'Головной отдел'), ('DEALER', 'Дилерский центр')], max_length=10, verbose_name='Тип точки'),
        ),
        migrations.AlterField(
            model_name='retailpointaddress',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='retailpointaddress',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='retailpointaddress',
            name='house_number',
            field=models.CharField(max_length=20, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='retailpointaddress',
            name='retail_point',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='address', serialize=False, to='retail_points.retailpoint', verbose_name='Торговая точка'),
        ),
        migrations.AlterField(
            model_name='retailpointaddress',
            name='street',
            field=models.CharField(max_length=200, verbose_name='Улица'),
        ),
    ]
