# Generated by Django 6.0.5 on 2026-06-01 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_points', '0002_alter_employee_options_alter_retailpoint_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники и доступ к API'},
        ),
    ]
