# Generated by Django 6.0.5 on 2026-06-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_points', '0003_employee_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='admin_visible_api_key',
            field=models.CharField(blank=True, help_text='Последний выданный ключ. Хранится для отображения в админке.', max_length=128, verbose_name='API-ключ (отображение)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='admin_visible_password',
            field=models.CharField(blank=True, help_text='Только для выдачи сотруднику через админку. Не используется для API-аутентификации.', max_length=128, verbose_name='Пароль для входа (отображение)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=30, unique=True, verbose_name='Телефон'),
        ),
    ]
