# Generated by Django 6.0.5 on 2026-05-30 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retail_points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('retail_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='retail_points.retailpoint')),
            ],
        ),
    ]
