# Generated by Django 6.0.5 on 2026-05-30 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('retail_points', '0002_alter_employee_options_alter_retailpoint_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointapikey',
            options={'verbose_name': 'Ключ API точки', 'verbose_name_plural': 'Ключи API точек'},
        ),
        migrations.AlterField(
            model_name='pointapikey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='pointapikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Истекает'),
        ),
        migrations.AlterField(
            model_name='pointapikey',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='pointapikey',
            name='key_hash',
            field=models.CharField(max_length=64, unique=True, verbose_name='Хеш ключа'),
        ),
        migrations.AlterField(
            model_name='pointapikey',
            name='retail_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='retail_points.retailpoint', verbose_name='Торговая точка'),
        ),
    ]
