# Generated by Django 6.0.5 on 2026-06-01 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_alter_pointapikey_options_and_more'),
        ('retail_points', '0003_employee_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64, unique=True, verbose_name='Хеш ключа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='retail_points.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'API-ключ сотрудника',
                'verbose_name_plural': 'API-ключи сотрудников',
            },
        ),
        migrations.DeleteModel(
            name='PointApiKey',
        ),
    ]
